### ISSUE TITLE
Homing Direction Invert firmware has incorrect options

### ISSUE THREAD

**Issue by Kerman** [Sienci-Labs/gsender#142]
The screen for invert home switch direction is incorrect, and it is impossible to set home switch directions.  

![image](https://user-images.githubusercontent.com/789531/185009008-da88870b-fe34-41f7-b541-0fda7f4175ab.png)

**Comment by Kerman** [comment]
this leaves you in a 'broken' state where you cannot clear the homing violation to access the firmware settings to disable homing.  (I had to tape a wrench to the sensor to trip it so i could disable homing)

**Comment by kglovern** [comment]
Thanks for reporting - we'll get it fixed in the next release.

In the meantime, for others having the same issue you can unlock the homing alarm using the unlock button in the top left of the visualizer and change the value in the gcode console manually over using a wrench.

![unlock](https://user-images.githubusercontent.com/22222507/185129603-6be425dd-1e82-4df9-98fa-9c6d1fd490d9.png)

**Comment by kglovern** [comment]
This will be fixed in 1.1.4 releasing later today.  Thanks for the report!
