### ISSUE TITLE
Firmware tool has missing GRBL options for machines with more than 3 axes

### ISSUE THREAD

**Issue by zalexzperez** [Sienci-Labs/gsender#166]
Hello,

I'm using grbl-mega-5x on my 4-axis machine (cloned X and Y, that is, two motors for X and two motors for Y).
The axes are defined as follows:
AXIS_1_NAME 'X'
AXIS_2_NAME 'Y' 
AXIS_3_NAME 'X'
AXIS_4_NAME 'Y' 

In the Firmware tool window, I set the "Generic CNC" profile. 
However, the firmware tool only shows settings for machines with X,Y and Z axes.
I understand the program is only conceived for 3-axis machines at the moment. 

What's interesting is that the exported json settings file does save my 4th axis settings, but unfortunately after importing this file and applying the settings, the 4th-axis settings are not applied in the grbl console. I think that's an inconsistency. 

Great program, by the way!

**Comment by SienciLabs** [comment]
Thanks Alejandro! 

Currently we don't have direct support for grbl MEGA 5X in gSender but are looking at options to alter how firmware settings are processed that could integrate the support you're looking for. The reason why it's not working presently is just that the Firmware tool is a fixed list that gets filled when machine connection happens, rather than a dynamic one. Hope to be making more progress on that as well as support for jogging of more than 3 axes in the coming 2 months
