### ISSUE TITLE
Using the PRB message after probing in the injected tool change code?

### ISSUE THREAD

**Issue by ModuloFS** [Sienci-Labs/gsender#187]
Hello,

is it possible to use /access the distance information of the PRB message (e.g. [PRB:151.000,149.000,-137.505:1]) after a probing command (e.g. G38.2) in the injected tool change code?
Is it also possible to store variables global between macro code and the injected code at a tool change? This would made the usage of  fixed tool length sensor possible.

**Comment by kglovern** [comment]
Hi

1) Any variable prefixed by "global" will be stored across the entire current connection instance since it's parsed down and stored as a JSON object.  

So, if we had a macro that stored some value (like a tool offset for your use case):
![image](https://user-images.githubusercontent.com/22222507/198041835-c6a8fd55-882f-492b-b355-9954534c5812.png)
![image](https://user-images.githubusercontent.com/22222507/198042082-f4bbbd5e-fe05-40d4-bdf9-1a769845e357.png)


We'd be able to access it in anything that uses the feeder (so not toolpaths, but yes for injected toolchange code, other macros, start/stop events, etc.):

![image](https://user-images.githubusercontent.com/22222507/198042186-8bd17e10-2c97-4512-b71d-f973c4e16f6e.png)


2) We don't save the results of a probe operation in the available context currently.  You can approximate it by saving the machine position as variables after a probe operation, but physical deceleration means they probably won't be exactly the same.

**Comment by ModuloFS** [comment]
Thank you for your fast answer!
Ok, the global variables are cool! 
I think i have a workaround for the probing. I am using FluidNC as grbl controller and it has a special probing G-command with an optional "P" parameter (http://wiki.fluidnc.com/en/config/probe) in which i am able to add an offset. The probing with the "P" parameter already sets my coordinate system to the right value at the probing event. So i should have no deceleration error.

**Comment by ModuloFS** [comment]
@kglovern you said in your comment above i can save the machine positions. How do I get access to the absolute machine position in macro code?

**Comment by ModuloFS** [comment]
Ok, i tried it out myself. Seems it is mposx, mposy and mposz.
