### ISSUE TITLE
Suspected bug: PRB parsing to params.PRB not aware of Rotary Axis

### ISSUE THREAD

**Issue by AndyCXL** [Sienci-Labs/gsender#386]
In testing, I suspect that the PRB data 'packet' when parsed is done so assuming X, Y and Z axes and fails if there is A (Rotary) axis present. For systems where Y is hijacked by the Rotary axis, only 3 elements will appear in the PRB, but for systems with permanent Rotary there are 4 elements

**Comment by kglovern** [comment]
Thanks, we'll take a look and adjust the parser as needed

**Comment by AndyCXL** [comment]
Excerpt from my GrblHAL controller $# output for parsing. Note 4 parameters (XYZA) but also note TLO has 4;
[TLO:0.000,0.000,0.000,0.000]
[PRB:-344.975,-13.891,-39.169,-3.000:1]

In GrblLineParserResultParameters.js the comments suggest 3 params for PRB and only 1 for TLO were in mind. The PRB list iterator does appear to strip as many list.length values are are given, but I don't know where/how these are pulled into the params.PRB structure, which to my mind narrows down where the issue may be;

        // [TLO:0.000]
        if (name === 'TLO') {
            payload.value = value;
        }

        // [PRB:0.000,0.000,1.492:1]
        if (name === 'PRB') {
            const axes = ['x', 'y', 'z', 'a', 'b', 'c'];
            const [str, result] = value.split(':');
            const list = str.split(',');
            payload.value = {};
            payload.value.result = Number(result);
            for (let i = 0; i < list.length; ++i) {
                payload.value[axes[i]] = list[i];
            }
        }

**Comment by kglovern** [comment]
Just to double check my sanity here - your board is running GRBLHal but you're currently doing testing connecting using the GBRL Controller or the GRBLHal controller?

PRB parsing wasn't implemented in the HAL controller as of 1.3.0 - it'll be in the next release (1.3.1).  So if you're using the HAL controller, you'll get a NAN error since PRB isn't available as a variable in 1.3.0 - it works fine using the grbl controller.   It works as expected in our internal build with params available as variables in both grblHAL and GRBL controllers - I was able to run your macro as posted on the forums without error.
