### ISSUE TITLE
Rapid override

### ISSUE THREAD

**Issue by Marty1109** [Sienci-Labs/gsender#436]
Anyway you can add a rapid override under the override tab. Be nice to start jobs at a slower pace to confirm movements at the start.

**Comment by kglovern** [comment]
That is what the slider does - major adjustments are done using the slider, minor adjustments with the buttons.  It's able to be used before the job as is.

**Comment by Marty1109** [comment]
i dont see a slide, what version was this added on? i only see a slide for feed rate and spindle speed overrides. nothing for rapids. i will add a screen shot later tonight when i am home.  believe i am on build v1.2.2

**Comment by Marty1109** [comment]
![image](https://github.com/Sienci-Labs/gsender/assets/154297148/bbd3edbe-f338-4e6c-b0a4-b3a9f66fba09)

![image](https://github.com/Sienci-Labs/gsender/assets/154297148/40a7384a-d7ed-4126-9027-68d6033a3f43)

**Comment by SienciLabs** [comment]
@Marty1109 I see you're asking about rapid overrides - we never chose to make room for this in the gSender UI since it's fairly non-typical for hobbyists to use. I think if you're wanting it then the feedback is fair to give though, maybe sometime in the future we could look to fit it in somewhere 👍
