### ISSUE TITLE
SLB firmware error

### ISSUE THREAD

**Issue by hamanjam** [Sienci-Labs/gsender#499]
Not sure if I need to, but I was trying to change Spindle1 to SBL_Spindle and disable all spindles.  (I have a PwnCNC so I can't get it to work just yet)

When I save firmware settings after changing $511, I get an error (Error 3 Invalid Statement) and the change does not save.  I tried on USB and Ethernet

![slb_firmware_error3](https://github.com/Sienci-Labs/gsender/assets/45050113/4fd5b7dc-e661-41bf-81c1-187e5a81ec9f)

**Comment by kglovern** [comment]
WEEE 0 indexing.

I think this is likely because you have the default spindle ($395) already set to SLB_SPINDLE and can't assign the same spindle twice.  The default spindle is spindle 0, not 1.

I'm able to recreate that error by setting $395 to another option (MODVFD) and attempting to set spindle 1 to MODVFD as well.  

If you just want SLB_SPINDLE enabled for the time being as you get your pwnCNC set up, setting $395 to SLB_SPINDLE and disable $511-513.  The $spindles command shows that setup as being correct (IE I can only use SLB_SPINDLE, nothing else is enabled.

![image](https://github.com/Sienci-Labs/gsender/assets/22222507/8b8365ce-5836-416a-850f-bce1f135b016)

Let me know if you're still running into issues.
